import java.util.ArrayList;

public class Database {
    public static ArrayList<String> hiraganaeng1 = new ArrayList<String>();
    public static ArrayList<String> hiraganajap1 = new ArrayList<String>();
    public static ArrayList<String> hiraganasyl1 = new ArrayList<String>();
    public static String[] hiraganaeng = {"love","blue","morning","foot","head","rain","house","pond","dog","younger sister",
            "above","sea","song","horse","plum","station","pencil","money","tea","younger brother",
            "man","stomach","woman","parent","music","face","key","wind","family","river",
            "north","fox","today","mouth","shoes","cloud","car","this morning","fight","voice",
            "heart, mind","answer","small bird","child","fish","cherry blossom","sugar","cold","monkey","salt",
            "below","to die","island","white","watermelon","sparrow","teacher","sky","shelf","to eat",
            "map","father","butterfly","moon","desk","wife","letter","weather","clock","friend",
            "bird","secret","name","Japan","doll","lukewarm","cat","throat","glue","flower/nose",
            "mother","east","person","beard","Mount Fuji","futon","boat","room","star","book",
            "every day","water","ear","insect","glasses","forest","mountain","snow","night","next week",
            "school bag","squirrel","apple","absence","zero","candle","I, me","bad","alcohol","sashimi",
            "grandmother","match, game","cow","sushi","tanuki, raccoon dog","sand","egg","hand","dream","iron",
            "morning sun","sunburn","jewelry","intersection","Osaka","kindness","feeling","memory","peach","vegetable",
            "hair/paper","ice","smoke","hot","cold to touch","Friday","Saturday","sleepy","secret","thin",
            "thick","road","water strider","kimono","strawberry","market","big","small","strong","weak",
            "chair","finger","warm","sour","sweet","bitter","salty","left","right","straight",
            "over there","next to","behind","in front","inside","outside","kitchen knife","siblings","older brother","father",
            "mother","older sister","grandfather","grandmother","rabbit","pig","white","black","red","painful",
            "safe","circle","mirror","smart","sad","dirty","clean/beautiful","airport","socks","mobile phone",
            "research","healthy","park","scary","wallet","magazine","work","snake","beard","water strider"};
    public static String[] hiraganajap = {"あい","あお","あさ","あし","あたま","あめ","いえ","いけ","いぬ","いもうと",
            "うえ","うみ","うた","うま","うめ","えき","えんぴつ","おかね","おちゃ","おとうと",
            "おとこ","おなか","おんな","おや","おんがく","かお","かぎ","かぜ","かぞく","かわ",
            "きた","きつね","きょう","くち","くつ","くも","くらま","けさ","けんか","こえ",
            "こころ","こたえ","ことり","こども","さかな","さくら","さとう","さむい","さる","しお",
            "した","しに","しま","しろ","すいか","すずめ","せんせい","そら","たな","たべる",
            "ちず","ちち","ちょう","つき","つくえ","つま","てがみ","てんき","とけい","ともだち",
            "とり","ないしょ","なまえ","にほん","にんぎょう","ぬるい","ねこ","のど","のり","はな",
            "はは","ひがし","ひと","ひげ","ふじさん","ふとん","ふね","へや","ほし","ほん",
            "まいにち","みず","みみ","むし","めがね","もり","やま","ゆき","よる","らいしゅう",
            "らんどせる","りす","りんご","るす","れい","ろうそく","わたし","わるい","さけ","さしみ",
            "そぼ","しあい","うし","すし","たぬき","すな","たまご","て","ゆめ","てつ",
            "あさひ","ひやけ","ほうせき","こうさてん","おおさか","しんせつ","きもち","きおく","もも","やさい",
            "かみ","こおり","けむり","あつい","つめたい","きんようび","どようび","ねむい","ひみつ","ほそい",
            "ふとい","みち","あめんぼ","きもの","いちご","いちば","おおきい","ちいさい","つよい","よわい",
            "いす","ゆび","あたたかい","すっぱい","あまい","にがい","しょっぱい","ひだり","みぎ","まっすぐ",
            "むこう","となり","うしろ","まえ","なか","そと","ほうちょう","きょうだい","あに","おとうさん",
            "おかあさん","あね","おじいさん","おばあさん","うさぎ","ぶた","しろい","くろい","あかい","いたい",
            "あんぜん","えん","かがみ","かしこい","かなしい","きたない","きれい","くうこう","くつした","けいたい",
            "けんきゅう","げんき","こうえん","こわい","さいふ","ざっし","しごと","へび","ひげ","あめんぼ"};
    public static String[] hiraganasyl = {"A-I", "A-O", "A-SA", "A-SHI", "A-TA-MA", "A-ME", "I-E", "I-KE", "I-NU", "I-MO-O-TO",
            "U-E", "U-MI", "U-TA", "U-MA", "U-ME", "E-KI", "E-N-PI-TSU", "O-KA-NE", "O-CHA", "O-TO-O-TO",
            "O-TO-KO", "O-NA-KA", "O-N-NA", "O-YA", "O-N-GA-KU", "KA-O", "KA-GI", "KA-ZE", "KA-ZO-KU", "KA-WA",
            "KI-TA", "KI-TSU-NE", "KYO-O", "KU-CHI", "KU-TSU", "KU-MO", "KU-RA-MA", "KE-SA", "KEN-KA", "KO-E",
            "KO-KO-RO", "KO-TA-E", "KO-TO-RI", "KO-DO-MO", "SA-KA-NA", "SA-KU-RA", "SA-TO-O", "SA-MU-I", "SA-RU", "SHI-O",
            "SHI-TA", "SHI-NI", "SHI-MA", "SHI-RO", "SU-I-KA", "SU-ZU-ME", "SEN-SE-I", "SO-RA", "TA-NA", "TA-BE-RU",
            "CHI-ZU", "CHI-CHI", "CHO-O", "TSU-KI", "TSU-KU-E", "TSU-MA", "TE-GA-MI", "TEN-KI", "TO-KE-I", "TO-MO-DA-CHI",
            "TO-RI", "NA-I-SHO", "NA-MA-E", "NI-HON", "NI-N-GYO-O", "NU-RU-I", "NE-KO", "NO-DO", "NO-RI", "HA-NA",
            "HA-HA", "HI-GA-SHI", "HI-TO", "HI-GE", "FU-JI-SA-N", "FU-TO-N", "FU-NE", "HE-YA", "HO-SHI", "HO-N",
            "MA-I-NI-CHI", "MI-ZU", "MI-MI", "MU-SHI", "ME-GA-NE", "MO-RI", "YA-MA", "YU-KI", "YO-RU", "RA-I-SHU-U",
            "RA-N-DO-SE-RU", "RI-SU", "RI-N-GO", "RU-SU", "RE-I", "RO-O-SO-KU", "WA-TA-SHI", "WA-RU-I", "SA-KE", "SA-SHI-MI",
            "SO-BO", "SHI-A-I", "U-SHI", "SU-SHI", "TA-NU-KI", "SU-NA", "TA-MA-GO", "TE", "YU-ME", "TE-TSU",
            "A-SA-HI", "HI-YA-KE", "HO-O-SE-KI", "KO-O-SA-TE-N", "O-O-SA-KA", "SHI-N-SE-TSU", "KI-MO-CHI", "KI-O-KU", "MO-MO", "YA-SA-I",
            "KA-MI", "KO-O-RI", "KE-MU-RI", "A-TSU-I", "TSU-ME-TA-I", "KI-N-YO-O-BI", "DO-YO-O-BI", "NE-MU-I", "HI-MI-TSU", "HO-SO-I",
            "FU-TO-I", "MI-CHI", "A-ME-N-BO", "KI-MO-NO", "I-CHI-GO", "I-CHI-BA", "O-O-KI-I", "CHI-I-SA-I", "TSU-YO-I", "YO-WA-I",
            "I-SU", "YU-BI", "A-TA-TA-KA-I", "SU-PA-I", "A-MA-I", "NI-GA-I", "SHO-PA-I", "HI-DA-RI", "MI-GI", "MA-S-SU-GU",
            "MU-KO-O", "TO-NA-RI", "U-SHI-RO", "MA-E", "NA-KA", "SO-TO", "HO-O-CHO-O", "KYO-O-DA-I", "A-NI", "O-TO-O-SA-N",
            "O-KA-A-SA-N", "A-NE", "O-JI-I-SA-N", "O-BA-A-SA-N", "U-SA-GI", "BU-TA", "SHI-RO-I", "KU-RO-I", "A-KA-I", "I-TA-I",
            "A-N-ZE-N", "E-N", "KA-GA-MI", "KA-SHI-KO-I", "KA-NA-SHI-I", "KI-TA-NA-I", "KI-RE-I", "KU-U-KO-O", "KU-TSU-SHI-TA", "KE-I-TA-I",
            "KE-N-KYU-U", "GE-N-KI", "KO-O-E-N", "KO-WA-I", "SA-I-FU", "ZA-S-SHI", "SHI-GO-TO", "HE-BI", "HI-GE", "A-ME-N-BO"};
}

